name: PR Checks

on: 
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]


jobs:
  swiftlint:

    name: SwiftLint

    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Run SwiftLint on all files
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict --force-exclude

  unit-tests:

    name: Unit Tests

    runs-on: macos-12

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Select Xcode 13.4
      run: sudo xcode-select -s /Applications/Xcode_13.4.app/Contents/Developer

    - name: Build and test
      run: |
        set -o pipefail && xcodebuild test \
          -scheme "DuckDuckGo" \
          -configuration "CI" \
          ENABLE_TESTABILITY=true \
          | xcpretty -r junit -o unittests.xml

    - name: Publish unit tests report
      uses: mikepenz/action-junit-report@v3
      with:
        report_paths: unittests.xml

